#!/bin/bash -e

REPO="tnagafuchi/dotfiles-test"
DOTFILES_DIR="$HOME/src/github.com/$REPO"

# run uname -a
uname -a

# Check macOS
if [ "$(uname)" != "Darwin" ] ; then
	echo "Not macOS!"
	exit 1
fi

# Check ararchitecture
if [ `uname -m` = 'x86_64' ] ; then
	echo "you ararchitecture is x86_64" 
	ARCH=x86_64
elif [ `uname -m` = 'arm64' ] ; then
	echo "you ararchitecture is arm64" 
	ARCH=arm64
fi

echo $ARCH
